<?php

/**
 * @file
 * Drupal hooks for the commerce_uuid module.
 */

/**
 * Implements hook_entity_info_alter().
 */
function commerce_uuid_entity_info_alter(&$entity_info) {
  $entity_info['commerce_product']['entity keys']['uuid'] = 'uuid';
  $entity_info['commerce_product']['uuid'] = TRUE;
}

/**
 * Implements hook_entity_uuid_load().
 */
function commerce_uuid_entity_uuid_load(&$entities, $entity_type) {
  if ($entity_type == 'commerce_product') {
    entity_property_id_to_uuid($entities, 'commerce_product', array('product_id'));
  }
}

/**
 * Implements hook_entity_uuid_presave().
 */
function commerce_uuid_entity_uuid_presave(&$entity, $entity_type) {
  if ($entity_type == 'commerce_product') {
    entity_property_uuid_to_id($entity, 'commerce_product', array('product_id'));
  }
}